### ISSUE TITLE
Emails from external people not being received

### ISSUE THREAD

**Issue by Kwameafranie** [SevnGroup/techops-recruitment#2]
External partners have been complaining that they send us mails and we don't recieve them. The logs were checked and the said emails never reached Kowri's email server. After a discussion with Google support, it was discovered that the http://mx.email-messaging.com/ mx record was intefering with the mails we were supposed to recieve. After some investigation, it was discovered that it belong to Infobip.

![Image](https://github.com/SevnGroup/techops-recruitment/assets/158052259/c84b8063-7442-4fe1-ab5a-88629016ea3b)

**Comment by kdjomeda** [comment]
@Kwameafranie  who is this assigned to. That's the status on this ?

**Comment by Kwameafranie** [comment]
> [@Kwameafranie](https://github.com/Kwameafranie) who is this assigned to. That's the status on this ?

@cathyamartDO has worked on it and it has been solved but I can't assign it to her. 

On the status of this item, the priority of mx.email-messaging was reduced to 2 and the missing emails appeared in the users inboxes. Also, no missing emails have been noticed since this change was done
